# infra/kubernetes/rbac/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecommerce-sa
  namespace: ecommerce
  annotations:
    azure.workload.identity/client-id: ""  # To be filled by deployment script

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ecommerce-cluster-role
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ecommerce-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: ecommerce-sa
  namespace: ecommerce
roleRef:
  kind: ClusterRole
  name: ecommerce-cluster-role
  apiGroup: rbac.authorization.k8s.io

---
